### ISSUE TITLE
Use GLib.get_os_info

### ISSUE THREAD

**Issue by worldofpeace** [elementary/switchboard-plug-about#112]
## Describe the bug
The code at https://github.com/elementary/switchboard-plug-about/blob/332b6102c0fc031dc6d919d54cb6252a19ee15f0/src/Plug.vala#L74 could be replaced by a function just added in GLib 2.63.1 https://tecnocode.co.uk/2019/11/01/g_get_os_info-and-glib-2-63-1/.
The code would be a lot simpler.

It's probably far off though, until that version can be used in elementary OS.

**Comment by danrabbit** [comment]
Done now :)
