### ISSUE TITLE
Update false

### ISSUE THREAD

**Issue by KanadSamanta** [elementary/switchboard-plug-about#121]
system update is not working. It says E: The repository 'http://ppa.launchpad.net/paolorotolo/android-studio/ubuntu bionic Release' does not have a Release file, while opening app store

**Comment by danrabbit** [comment]
This is an error with a 3rd party repository that you have added. You'll need to remove the android studio PPA.

Closing as "Out of scope" since this is an error with a 3rd party repo and not with elementary OS
