### ISSUE TITLE
Cannot identify Pinebook Pro

### ISSUE THREAD

**Issue by danrabbit** [elementary/switchboard-plug-about#127]
Not only are we unable to identify the processor and graphics, but we also don't event recognize this as a laptop

![Screenshot from 2020-07-21 16 58 33](https://user-images.githubusercontent.com/7277719/88118834-88802b00-cb73-11ea-826e-5bb9cd8ae1c7.png)

**Comment by davidmhewitt** [comment]
Graphics will be solved by #125 / #130 

The fact it isn't identified as a laptop is down to systemd. It tries to use ACPI and/or DMI to identify it. These both rely on some firmware on the device that speaks those protocols. Unfortunately they're quite PC centric standards and AFAIK there aren't many ARM boards that do that natively, especially not ones without a UEFI implementation. I don't think there really is any firmware on the Pinebook that would allow *any* software to identify it as a notebook. However, it looks like we can override this in systemd with an `/etc/machine-info` file that we could build into the image.

I'll look into the CPU thing and see if there's a better way we can do this.

**Comment by danrabbit** [comment]
Sounds like this is resolved now as far as we can control here
