### ISSUE TITLE
Plug appears to be destroyed when navigating away

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-about#145]
## What Happened

When you hit "All Settings" to leave the About plug, the plug contents themselves seem to disappear. This is made more obvious since https://github.com/elementary/switchboard/pull/181, where it also breaks the animation.

## Expected Behavior

Navigating away from the About plug is smooth and matches the other plugs.

## Steps to Reproduce

1. Open the About plug
2. Hit "All Settings" to leave it

## Platform Information

elementary OS 6 daily, running Switchboard master from Git.

**Comment by cassidyjames** [comment]
This looks suspect, maybe?

https://github.com/elementary/switchboard-plug-about/blob/8141faa2a8c477c9d63fbb71199efd3c56a9f5c5/src/Plug.vala#L50-L52

**Comment by pongloongyeat** [comment]
> https://github.com/elementary/switchboard-plug-about/blob/8141faa2a8c477c9d63fbb71199efd3c56a9f5c5/src/Plug.vala#L50-L52

That does seem to be the issue. Should I open a PR for it?
