### ISSUE TITLE
Fallback icon is a laptop on Mac Mini 2014

### ISSUE THREAD

**Issue by andirsun** [elementary/switchboard-plug-about#148]
## Problem

Hi, I just install elementary in my mac mini 2014, but the device icon is a laptop instead a mac mini.

## Proposal

I want to know If it would be possible to add a mac mini device icon and the name of "mac mini late 2014". 
Example of icon : 
![mac-mini-super-mac-mini-3-800-x-800-icon-png-icon-removebg-preview](https://user-images.githubusercontent.com/22928302/99475958-a0976980-291d-11eb-804f-46c69a6c5b14.png)

## Prior Art

![Screenshot from 2020-11-17 19 18 16](https://user-images.githubusercontent.com/22928302/99475530-bb1d1300-291c-11eb-9954-120b6d40f4fc.png)

**Comment by cassidyjames** [comment]
Specific information (like an actual Mac Mini graphic and specific model details) is expected to be provided by the OEM. I _thought_ we showed a desktop display when it's not a desktop, but I'd have to dig into the code to look at that. For now, I will consider the issue that we show a laptop instead of a desktop display for a Mac Mini. :smile:

**Comment by JoseExposito** [comment]
I can confirm that a monitor is displayed when running on desktop.

**Comment by cassidyjames** [comment]
@andirsun so from this (and other issues filed), it sounds like some underlying component is detecting your Mac Mini as a laptop. Unfortunately I'm not sure that there's much we can do in this codebase if the underlying system is providing incorrect information.

**Comment by andirsun** [comment]
@cassidyjames what do you think
## Before
![Screenshot from 2021-08-23 11 11 52](https://user-images.githubusercontent.com/22928302/130481391-8f45fa3d-596a-4e3a-890a-a9a449abff54.png)
## After
![Screenshot from 2021-08-23 11 10 33](https://user-images.githubusercontent.com/22928302/130481423-7f9d9b30-9b44-4a1c-98b1-26209e75b67d.png)

**Comment by danrabbit** [comment]
This information comes from the `icon-name` property on the `org.freedesktop.hostname1` interface. You can check that with the app D-Feet to verify the value it's reporting. It might also be worth seeing if there's a difference in the `chassis` property, I suppose.

![Screenshot from 2021-08-23 09 35 31](https://user-images.githubusercontent.com/7277719/130484335-88d3dc65-77d3-420f-9f15-156be6063684.png)

If the information here is incorrect, that would be an issue in `systemd-hostnamed` which it looks like you can report issues here: https://github.com/systemd/systemd/issues
