### ISSUE TITLE
Distributor and manufacturer logo images are of different sizes

### ISSUE THREAD

**Issue by pongloongyeat** [elementary/switchboard-plug-about#163]
## What Happened
As title implies. Not sure if this issue needs to be filed tho since I'm sure the OSView and HardwareView are still being iterated on.

## Expected Behavior
Icon sizes should be the same and labels should align horizontally. I'm using the default fallback images.

## Steps to Reproduce

![screen-capture (2)](https://user-images.githubusercontent.com/31680656/103658177-d82da400-4fa5-11eb-9de1-62c9db35c2cb.gif)

1. Switch between OSView and HardwareView.
2. See horizontal position of labels.

## Platform Information
eOS6, own branch of about plug (no design changes, essentially master).

**Comment by danrabbit** [comment]
This should be resolved now that we're using Hdy.Avatar to generate a more interesting logo image
