### ISSUE TITLE
Logo on about screen

### ISSUE THREAD

**Issue by nightfire68** [elementary/switchboard-plug-about#181]
On the about screen in the setting on Elementary OS 5.1.7 is showing the Debian logo, rather than the Elementary OS logo.
![Screenshot from 2021-01-26 10-31-38](https://user-images.githubusercontent.com/26495625/105866196-bd0ced80-5fc1-11eb-9d45-136c73deb667.png)

**Comment by cassidyjames** [comment]
It looks like you have changed the system-wide icons which is not a setting that is exposed in elementary OS. The third-party icon theme has replaced the OS logo.

**Comment by nightfire68** [comment]
Oh, XD that would explain it lol> It looks like you have changed the system-wide icons which is not a setting that is exposed in elementary OS. The third-party icon theme has replaced the OS logo.
