### ISSUE TITLE
Firmware page needs to actually explain what a firmware is

### ISSUE THREAD

**Issue by hanaral** [elementary/switchboard-plug-about#196]
## Problem

Everyone has heard what a firmware is and also likely knows it has something to do with computers and things that are firm, but the average person will not actually know what it really is.

## Proposal

elementary OS is not an IT guidebook but I see no reason to give the firmware page at least some text and maybe even an icon, in a visually consistent way to the Network and Bluetooth plugs.

## Prior Art

![Screenshot from 2021-02-05 18-32-53](https://user-images.githubusercontent.com/58219504/107074557-d0e5fa00-67e0-11eb-9de5-a0a8dca3292e.png)

**Comment by cassidyjames** [comment]
We initially had an icon, title, and description planned for this page, but it felt a little redundant to have the tab named "Firmware" with a big heading right below it saying "Firmware". But I agree this page could be a little more informative. :+1:
