### ISSUE TITLE
AMD Radeon rx in lowercase

### ISSUE THREAD

**Issue by davidak** [elementary/switchboard-plug-about#223]
## What Happened

the rx is displayed lowercase, but the official product name is using uppercase

https://www.amd.com/en/RX-series

![Screenshot from 2021-07-24 04-03-55](https://user-images.githubusercontent.com/91113/126866856-c9234e94-1c12-4b7b-920e-77c6f789ae35.png)

## Expected Behavior
It should say "AMD Radeon RX 480"

## Steps to Reproduce

1. Open system settings
2. click System
3. click Hardware

## Platform Information

NixOS 21.11.git.15c41b3a133 (Porcupine)
switchboard-plug-about 6.0.0

**Comment by vjr** [comment]
Even AMD CPU names (at least Ryzen) seem to be going lowercase due to the regexes. I'll see if I can tweak them to not mess with the names...

**Comment by lenemter** [comment]
@vjr You've fixed this in #250, right?

**Comment by vjr** [comment]
@lenemter I believe so, yes.

**Comment by lenemter** [comment]
Ok. I'll close this. @davidak if you still encounter this issue reply here please.
