### ISSUE TITLE
Wallpaper placeholder is visible behind elementary logo during navigation to plug

### ISSUE THREAD

**Issue by jlnr** [elementary/switchboard-plug-about#272]
### What Happened?

When first opening this plug, the logo changes while the page is being animated in.

After the animation finishes, there is a faint inner "e" inside the outer "e". I don't think this is intentional?

https://github.com/elementary/switchboard-plug-about/assets/70772/578a24f5-2369-4a9f-bf5a-e282fb065c8c

### Steps to Reproduce

1. Open Switchboard
2. Open "About" plug

### Expected Behavior

The logo being shown is always the right one.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

This is in a live session from the 2023-09-07 Daily ISO on a MacBook Pro.

**Comment by danirabbit** [comment]
Yeah because you're on daily the wallpaper being used here is the daily wallpaper which has a logo in it. So that's to be expected

**Comment by jlnr** [comment]
I took another look at the video and the code, and adjusted the issue title accordingly. The double "e" looks a bit odd but is correct. However, the other placeholder (in the middle of the video) should probably not be visible.

Maybe there's a way to only fade in the image view once it has finished loading.

**Comment by danirabbit** [comment]
I can't reproduce this in the GTK 4 port. @jlnr can you still reproduce this with the latest from `main`? Note that you'll need to run `io.elementary.settings` and not `io.elementary.switchboard`

**Comment by jlnr** [comment]
Oof, sorry, I totally missed this GitHub notification. =( Thanks for looking into it and @leolost2605 for the fix 🙏
