### ISSUE TITLE
HELLO => SOS VPN impossible avec Elementary 7.1

### ISSUE THREAD

**Issue by mahe9595** [elementary/switchboard-plug-about#298]
### What Happened?

Pourquoi il n'est pas possible d'utiliser un VPN avec elementary 
idem pour une firewall
je précise qu'il est impossible d'utiliser PROTON VPN 
autre chose lorsque le DNS est mort comment le regénérer car la commande normale sous linux ne fonctionne pas 
SOS
MERCI

### Steps to Reproduce

sss

### Expected Behavior

xsdc

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
sderf
```

### Hardware Info

azert

**Comment by tintou** [comment]
You have to follow the tutorial at https://protonvpn.com/support/linux-openvpn/#NetworkManager it is just working the same on elementary.
