### ISSUE TITLE
Progress indicator when downloading updates

### ISSUE THREAD

**Issue by danirabbit** [elementary/switchboard-plug-about#310]
### Problem

When downloading quite a lot of updates the view redundantly shows "downloading" without any kind of indication of how long this might take.

![Screenshot from 2024-02-20 19 45 20@2x](https://github.com/elementary/switchboard-plug-about/assets/7277719/40f83ff9-f4e3-4e82-8ae3-4ebce94cc3f5)

### Proposal

It would be nice to have a progressbar or at least like "10/200 MB" to have an idea that there is progress being made

**Comment by seifeldinio** [comment]
I've created three mockups to visualize potential solutions:

**Time Remaining**
An estimated time remaining for the download to complete

![Time](https://github.com/user-attachments/assets/4078b437-5337-488d-a470-4aec663b1a5c)



**File Size Progress**
The amount of data downloaded out of the total download size

![MB](https://github.com/user-attachments/assets/c7b90095-c9e3-425f-a527-6bf575dc470b)



**The Number of Completed Updates**
Indicates the number of completed updates out of the total

![Tasks](https://github.com/user-attachments/assets/29be37ef-9132-4e43-baa9-c6ef1c1f0575)


I think providing this progress indicator is important for the **visibility of system status**, ensuring users have a clear understanding of the update process and reducing uncertainty during updates.

Would love to hear your feedback on this!

**Comment by teamcons** [comment]
Time estimation, while maybe less reliable than the others, is the most actionable for the user

I know i have to keep my computer on for at least 20mn, i can plan on it
500mb, all i can think of is "oo big updat"
10 updates, does not give indication of size or how impactful

**Comment by alainm23** [comment]
Hello team, I was reviewing and working on this feature. To check the update status, the [Pk.Progress](https://valadoc.org/packagekit-glib2/Pk.Progress.html) object is used, and it provides the values for `download_size_remaining`, `percentage`, and `remaining_time`. Personally, I also like using the remaining download size, as I think it's a more reliable indicator.
