### ISSUE TITLE
None of the experimental builds of EOS8 work on any of my computers.

### ISSUE THREAD

**Issue by CuriousCoconut** [elementary/switchboard-plug-about#317]
### What Happened?

I have tried all of the experimental builds for EOS8 and they do not work on any of my computers. The older ones don't work at all and never boot after selecting the option to boot from a live USB. I just get the spinning thing and then a black screen. The newer EOS8 builds will get to a screen with the elementary logo on it and a cursor but nothing else. When leaving that screen open eventually that screen disappears too and I'm left with just a black screen.

### Steps to Reproduce

1. Create a USB from the .iso file.
2. Insert USB in powered down computer. Power computer on and select option from boot menu to boot from USB.
3. Select either "try or install elementary os" or "try or install with safe graphics"
4. A page shows up with a blurry elementary OS logo and a cursor but nothing else, then it eventually goes to a black screen.
5. On one of my computers it gets stuck in a boot loop where it keeps showing the Dell logo plus the elementary loading spinner and then restarts to that screen over and over. On another computer I just get the screen with the cursor.

### Expected Behavior

The expected behavior is that when booting from the live USB it would give you a preview version of the OS along with the option to install it.

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Hardware Info

The hardware doesn't seem to make a difference as the issue is the same across multiple devices which all have different hardware.

**Comment by danirabbit** [comment]
Hey thanks for your report. We're aware of the issue and it should be resolved soon. We're tracking it here https://github.com/elementary/os/issues/710

closing as a duplicate
