### ISSUE TITLE
Show sponsor goal progress bar

### ISSUE THREAD

**Issue by danirabbit** [elementary/switchboard-plug-about#329]
### Problem

Want to drive engagement towards sponsorship

### Proposal

Show a progress bar representing our current sponsor goal completion. Can use a graphql query:

```
query {
  organization(login: "elementary") {
		sponsorsListing {
      activeGoal {
        percentComplete
      }
    }
  }
}
```

**Comment by teamcons** [comment]
May i have my hand at a design ?

Maybe we can straight up show a tab for this, with a list of nicknames of sponsors and sponsor organizations starting a specific tier
Maybe that could motivate people too

**Comment by teamcons** [comment]
Okay so
this sounds like monologuing, my apologies. Random ideas that may not be good but could be leads for someone to come up with better.

A progress bar in the first tab at first sounded to me clutter-y. There are already the links, and the update thing. It made a page with two purposes : Promotion, Maintenance.

So i went on the thought that it may be best served with a tab that is a bit more "About" - after all the plug has more or less drifted into "System". So a tab with "About" mentioning financing goals ? And links to contribute ? That sounded like a good start. But what is the plan ?

Maybe there is a better way to encourage people to go from curious passerby and passive user to a sense of "yes ! Im contributing to my OS !", and there are several ways - all of which require the user to click on the link.
So the bottleneck is the link. People have to find the "involve" link in the list of links then click and be slammed with a world of possibilities

So why not expose more ?
Bar with financing goals, and a "help us expand eOS !". but financing is not the only one
Why not then a progressbar with language ? Most users know at least a little bit their language. "Oh, theres a bar for my system language. OH Abkazian isnt 100% ?? I am Abkazian! I can do that! Click."
Why not give a face to the core team ? Like any About should have. A profile picture and short bio of Danielle and other looongstanding contributors
Why not expand on the tiers ? Have the nickname of bigger sponsors be mentioned. Thanks ~SEXYFURBY69~ and +V4L4L0rD+ for your monthly support :3
Why not speak particularly to other devs, who may also bring assistance? Want to help ? Here is the link to current confirmed bugs. Or needs-design table for future evolutions.

If anything there is potential beyond the financing goals, and opportunity to create a sense of community, both as an end and as a means to its survival through financing goals.
So why not rename this plug and have a new, true, "About" or "Community" plug ? With some kind of overview of how elementary is doing: % for each language, financing goals, actively tracked bugs...
But then i think that may be super pushy, and marketing-sounding... After all this is still about something that goes in the Settings. And theres some weirdly conservative members who get very aggressive when it comes to money - theres a trend in Open Source of end users who think software comes out of thin air, the connexion is a bit lost with involvement of any kind.
The big distros arent so interested in desktop, their money comes from server. So connection with the end user is a niche elementary OS _could_ take. That is how the distribution survives after all - And that is consistent with its values, and its efforts (such as the focus on accessibility...)

Word soup, word soup. Going a bit far here. But i think thats a really good idea you had, that also "brings" in front of the user the efforts to build the DE they want to use.

**Comment by teamcons** [comment]
Very raw idea of an additional tab to encourage people to help. We could call it "Community"

The presentation is ugly and really perfectible, but i wanted to put it out and get other people's thinking rolling

![About tab](https://github.com/user-attachments/assets/52992c99-ebce-4905-9fdd-25e719e5fa22)

**Comment by alainm23** [comment]
For now, we could start with something simple

![image](https://github.com/user-attachments/assets/0819dc1a-cfba-4c6f-a506-997741169d3f)

**Comment by danirabbit** [comment]
@alainm23 That's almost exactly what I was picturing. Could make the progressbar a bit more cute with some CSS but that's perfect

**Comment by alainm23** [comment]
I will keep it in mind, for now I will finish with connecting the API and get the real sponsor goal.

**Comment by teamcons** [comment]
A bit more emphasis ! Sponsor us !
im unsure whether to connect it with the list below (because same topic)
or detached like your design (because more visible/eyecatching)

**Comment by teamcons** [comment]
I am hyped about this pull request.

**Comment by teamcons** [comment]
I didnt notice the alternating text
It may be perceived as a bit tacky and irritating. Like a commercial billboard.

Maybe we can smush them together? the window has a minimum size anyway

**Comment by alainm23** [comment]
I already have all the code working, only I have a detail with the personal token of Github, it does not let me upload it, it is a personal one and with only access to read public repositories.

![image](https://github.com/user-attachments/assets/112b5171-df9c-4aad-94a0-54e281569988)

**Comment by alainm23** [comment]
I found a way to upload the personal token, it's a bit weird but it works 😅️
https://github.com/elementary/switchboard-plug-about/blob/alainm23/fix-329/src/Views/OperatingSystemView.vala#L799

**Comment by danirabbit** [comment]
> Very raw idea of an additional tab to encourage people to help. We could call it "Community"
> 
> The presentation is ugly and really perfectible, but i wanted to put it out and get other people's thinking rolling
> 
> ![About tab](https://private-user-images.githubusercontent.com/147658063/385293278-52992c99-ebce-4905-9fdd-25e719e5fa22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MjQ0MTIsIm5iZiI6MTczMzUyNDExMiwicGF0aCI6Ii8xNDc2NTgwNjMvMzg1MjkzMjc4LTUyOTkyYzk5LWViY2UtNDkwNS05ZmRkLTI1ZTcxOWU1ZmEyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQyMjI4MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTk3NjI2YmJiMzZkMmU5MzJmNDcwNTM3M2VmNTBlNjRkNjVlNGU4N2NhZWE0MThjYjdlYzU1YjdmMDc4ZjZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PovTAZdmPC_VTP69aGM4IN6M8z7P9Y6gVvLnHv7RN0g)

This issue will probably be closed as completed very soon, so you might want to open a new issue or discussion with some of this other ideation so it doesn't get lost
