### ISSUE TITLE
Refreshing update check does not refresh "Last refreshed"

### ISSUE THREAD

**Issue by teamcons** [elementary/switchboard-plug-about#342]
### What Happened?

Manually checking whether there is a new update does not refresh the widget "memory" of when was the last check.

### Steps to Reproduce

Do not check for any update for at least an hour. (Untoggle automatic check too)
Go to System
"Last checked: XX mn ago"
Click refresh, wait for refresh
Unchanged: "Last checked: XX mn ago"

### Expected Behavior

"Last checked: Right now"

We could say this bug is not very refreshing

### OS Version

8.x (Early Access)

### Session Type

Secure Session (Wayland)

### Software Version

Latest release (I have run all updates)

**Comment by UncleTallest** [comment]
Can verify that this is the case but it isn't the only wonky thing about the last refreshed value. Yesterday evening it was time-travelling on me. 
![image](https://github.com/user-attachments/assets/d7921b89-bbae-49ee-85a5-a37775472f43)
