### ISSUE TITLE
Built on Ubuntu 16.04.2 in “About”

### ISSUE THREAD

**Issue by ultraviolet-1986** [elementary/switchboard-plug-about#38]
Small issue, not breaking or anything. The line Built on "Ubuntu 16.04.2 LTS" in "About" on the settings page should be Built on "Ubuntu 16.04.3 LTS".

16.04.3 was released a short time ago so any elementary OS systems up-to-date will be up to Ubuntu 16.04.3 I assume?

Thanks,

William

NOTE: Apologies for placing in the wrong section previously: <https://elementaryos.stackexchange.com/questions/13045/built-on-ubuntu-16-04-2-in-about>

**Comment by matzipan** [comment]
As far as I can tell, this string is read programatically from the system config files, so perhaps your system does not run 16.04.3?

**Comment by ultraviolet-1986** [comment]
I'm currently fully up-to-date on elementary at the time of writing but I have to admit that I am unsure exactly which components of the Ubuntu base are inherited as part of this OS - it may be that these components are still at 16.04.2 but I can't say for sure.

Does this mean that every up-to-date instance of elementary will report `16.04.2` at the moment? If so, then this is likely a non-issue - it's minutiae anyway but because of an Ubuntu base I can only assume that an up-to-date system should report 16.04.3.

**Update:** A quick glance through the source shows that `\etc\os-release` has no reference to the Ubuntu version number and this is referenced by this plug to gather system info, but there's a `\\FIXME` in for this variable that doesn't seem to exist yet. It may be hard-coded elsewhere.

**Comment by ultraviolet-1986** [comment]
I'm currently fully up-to-date on elementary at the time of writing but I have to admit that I am unsure exactly which components of the Ubuntu base are inherited as part of this OS - it may be that these components are still at 16.04.2 but I can't say for sure.

Does this mean that every up-to-date instance of elementary will report `16.04.2` at the moment? If so, then this is likely a non-issue - it's minutiae anyway but because of an Ubuntu base I can only assume that an up-to-date system should report 16.04.3.

**Update:** A quick glance through the source shows that `\etc\os-release` has no reference to the Ubuntu version number and this is referenced by this plug to gather system info, but there's a `\\FIXME` in for this variable that doesn't seem to exist yet. It may be hard-coded elsewhere.

Sorry, posting last reply appeared to have closed this, copied and pasted for re-opening.

**Comment by btkostner** [comment]
Reporting from a mostly clean elementary install:

```
elementary OS 0.4.1 Loki (64-bit)
Built on "Ubuntu 16.04.2 LTS"
Linux 4.10.0-32-generic
GTK+ 3.18.9
```

**Comment by ultraviolet-1986** [comment]
Needed to spin up a VM and test another machine for something else I'm looking into - both of them also report 16.04.2 with all updates applied.

**Comment by ultraviolet-1986** [comment]
Just updated today and the 'About' page now states **16.04.3** - thank you all very much. I'll close this as resolved.

Cheers!
