### ISSUE TITLE
'Check for Updates' is not working anymore

### ISSUE THREAD

**Issue by J0Ar** [elementary/switchboard-plug-about#41]
Nothing more to say i think

**Comment by btkostner** [comment]
Seems to be working here.

What version of elementary are you running? (about plug)
What version of switchboard plug are you using? (`sudo dpkg-query -W switchboard-plug-about`)
What version of AppCenter are you using? (`appcenter -a` or `io.elementary.appcenter -a`)

**Comment by codygarver** [comment]
Fixed in new update.

**Comment by J0Ar** [comment]
elementary OS 0.4.1 loki (stable with all updates, Installed on monday)
switchboard-plug-about 0.2.3.1-0~512~ubuntu0.4.1.1
Appcenter 0.2.6

Thanks Cody :)
