### ISSUE TITLE
Clicking "Check for Updates" does not take you to the update page

### ISSUE THREAD

**Issue by Jacob8765** [elementary/switchboard-plug-about#44]
Upon going to the about page in settings, clicking the "Check for Updates" button takes you to the Appcenter home page. It should instead take you to the updates page. I am on elementary OS 0.4.1 Loki.

**Comment by cassidyjames** [comment]
Thanks for reporting! This looks like it's actually in issue in AppCenter itself. The plug is doing the right thing.

**Comment by cassidyjames** [comment]
You can follow the other issue at https://github.com/elementary/appcenter/issues/595
