### ISSUE TITLE
Wrong CPU infos

### ISSUE THREAD

**Issue by karim-inabi** [elementary/switchboard-plug-about#64]
-The info tab in the settings is telling me that my CPU is dual core while its actually a Quad core one .
-Using a SYSTEM MONITOR app it shows me 4 core running .
-Hoping for a fix thanks.
![screenshot from 2018-07-24 20-06-20](https://user-images.githubusercontent.com/40875295/43160505-3d7a8de6-8f7d-11e8-86df-911319b3a5c4.png)
![screenshot from 2018-07-24 20-08-25](https://user-images.githubusercontent.com/40875295/43160547-69806ab4-8f7d-11e8-815e-3735111a4207.png)

**Comment by Djaler** [comment]
Your CPU is actually has 2 core. It uses technology named Hyperthreading. For each processor core that is physically present, the operating system addresses two virtual (logical) cores.

**Comment by davidmhewitt** [comment]
Thank you for taking the time to report a potential issue.

The Intel website has a handy specification list for all of their CPUs. Here is the page for yours:

https://ark.intel.com/products/85212/Intel-Core-i5-5200U-Processor-3M-Cache-up-to-2_70-GHz

It does indeed have 2 cores so the settings page is correct, so I'll close this issue.

**Comment by karim-inabi** [comment]
ok thanks so much ive got it now
