### ISSUE TITLE
[Suggestion]  Add a "Suggestion to Devs / General Bug Report" to About Panel

### ISSUE THREAD

**Issue by ph4nt0m117** [elementary/switchboard-plug-about#77]
I'm super stoked about elementary and its been the best experience I've had on the desktop in the last 11 years of me being a linux user, but I'd love to see a "Suggest Improvements" in the "About" panel.  I see a lot of stuff on Reddit for improvements but nothing that seems very official.

For example.  The elementary tweaks app doesn't work!  I'd love an official app that could be in the store.  If it had to be a paid only app even, because I know the devs have a vision for the OS, and I'd have to pay a dollar, I'd be good with that 100%.  I want to be able to change only a few things (dark mode, desktop icons / desktop drawer tablet style for dtop icons, etc ideas) but is there an official channel that is going to get seen?  And even if it just goes to a reddit page, I'd still love for there to be something there.  Thanks!

**Comment by peteruithoven** [comment]
We generally use issues for this. Maybe Reddit or the community Slack for more general discussions. I don't think we want to create another list. There for example have been many discussions on the issue you mention.

I do understand that suggesting an improvement through a "Report a problem" buttons is counter intuitive, but "Report a problem / suggest an improvement" would be a rather long name.
