### ISSUE TITLE
Epiphany missing in Report a problem dialog

### ISSUE THREAD

**Issue by peteruithoven** [elementary/switchboard-plug-about#85]
The Epiphany browser is missing in the *Report a problem* dialog.
![screenshot from 2019-01-04 17 37 03](https://user-images.githubusercontent.com/523210/50699208-78fbc880-1047-11e9-97eb-2edbd0d125e4.png)

It should probably link to https://gitlab.gnome.org/GNOME/epiphany/ ?

**Comment by danrabbit** [comment]
I think we might want some feedback from @mcatanzaro about whether he wants Epiphany issues from elementary OS users in GitLab or if he would prefer them to go to a separate tracker since we have some downstream patches

**Comment by mcatanzaro** [comment]
Hm, as long as you have a recent version, reporting upstream is fine. I don't mind redirecting users to the downstream bugtracker whenever an elementary patch is implicated. That shouldn't happen very often.

One complication is that we don't accept web content bug reports on the Epiphany issue tracker; these should be reported to WebKit Bugzilla instead. How does the problem reporting app work? Does it just link to the upstream bugtracker? If so, you could link to https://gitlab.gnome.org/GNOME/epiphany/blob/master/CONTRIBUTING.md I suppose, something like that?
